[DPE-3862] Switch to reusable workflows and add arm64 builds (#31)
* Poetry

* Workflows

* Charmcraft override

* Set groups

* Bump libs

* Add arm64 base

* Revert lib check flow

* Code review improvements

* Bump lock

* Update CONTRIBUTING.md

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

* Old build workflow

---------

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -4,12 +4,18 @@ type: charm
 parts:
   charm:
     build-packages: [git]
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
+    charm-strict-dependencies: true
 bases:
-  - build-on:
-    - name: ubuntu
-      channel: '22.04'
-      architectures: [amd64]
-    run-on:
-    - name: ubuntu
-      channel: '22.04'
-      architectures: [amd64]
+  - name: ubuntu
+    channel: "22.04"
+    architectures: [amd64]
+  - name: ubuntu
+    channel: "22.04"
+    architectures: [arm64]
